### ISSUE TITLE
Config File not exist

### ISSUE THREAD

**Issue by Kyzak11** [Locossss/Roblox-DMX#1]
I can't execute the exe file, i have an error "config gile not exits"
![image](https://user-images.githubusercontent.com/80856585/194756801-2ffd1c3b-d840-4ba6-b79b-68bb6dba79ac.png)

**Comment by Locardium** [comment]
Download it from the [release](https://github.com/Locossss/Roblox-DMX/releases/download/2.0/Release.rar) and extract the winrar with **all** the files.
